-- Update script to set starting bids and artwork descriptions without dropping the database
UPDATE items SET starting_bid = 45, desc_placeholder = 'A charming portrait capturing the loyal and heartwarming expression of a beloved dog. Rich textures and warm tones bring this faithful companion to life, making it a perfect addition to any space.' WHERE creative_name = 'Canine Canvas';
UPDATE items SET starting_bid = 75, desc_placeholder = 'A bold, pop-art style portrait depicting a subject blowing a giant pink bubblegum bubble. Full of vibrant colors and whimsical energy, this statement piece adds a playful, modern touch to your room.' WHERE creative_name = 'Bubblegum Dreams';
UPDATE items SET starting_bid = 35, desc_placeholder = 'A small-scale, atmospheric depiction of an urban transit scene. Capturing the motion, lights, and gritty charm of the city subway system, this miniature brings a slice of metropolitan life to your collection.' WHERE creative_name = 'Transit Miniature';
UPDATE items SET starting_bid = 275, desc_placeholder = 'A stunning explosion of colors, this piece features a detailed arrangement of multi-colored flowers. The intricate details and vivid color palette create a lively, refreshing focal point.' WHERE creative_name = 'Prismatic Petals';
UPDATE items SET starting_bid = 35, desc_placeholder = 'An artistic close-up of a paintbrush, celebrating the tool of creation. A beautiful study of textures and the promise of a blank canvas, perfect for artists and creative spirits.' WHERE creative_name = 'The Creator''s Tool';
UPDATE items SET starting_bid = 75, desc_placeholder = 'A delicate, elegant close-up of a pink flower in full bloom. Its soft petals, gentle lighting, and pastel hues bring a sense of serenity, natural beauty, and calm to your home.' WHERE creative_name = 'Roseate Bloom';
UPDATE items SET starting_bid = 75, desc_placeholder = 'A captivating figurative portrait rendered in soft pink and blush tones. Combining modern style with emotional depth, this elegant piece captures a quiet, introspective moment.' WHERE creative_name = 'Blush Portrait';
UPDATE items SET starting_bid = 650, desc_placeholder = 'A breathtaking, large-scale contemporary painting featuring cascading waves of vibrant, rainbow-colored hair. The dynamic movement and brilliant color spectrum make this a showstopping center of attention.' WHERE creative_name = 'Spectrum Tresses';
UPDATE items SET starting_bid = 125, desc_placeholder = 'A stylish and dramatic portrait featuring a subject surrounded by wisps of smoke. Its high-contrast, moody aesthetic evokes vintage cinema and mysterious allure.' WHERE creative_name = 'Smokescreen Silhouette';
UPDATE items SET starting_bid = 335, desc_placeholder = 'A large, striking representation of a bustling metropolitan subway station. Bold lines and deep perspective draw the viewer into the rhythmic, energetic heartbeat of city transit.' WHERE creative_name = 'Metropolitan Transit';
UPDATE items SET starting_bid = 75, desc_placeholder = 'A chic and stylish pop-art portrait featuring a subject wearing iconic sunglasses. With its cool, nonchalant attitude and bold modern colors, it brings an instant touch of contemporary style.' WHERE creative_name = 'Shaded Gaze';
UPDATE items SET starting_bid = 75, desc_placeholder = 'An intriguing and atmospheric depiction of a tunnel, playing with light, shadow, and deep perspective. A captivating abstract study of journey, transition, and architectural depth.' WHERE creative_name = 'Echoes of the Underground';
UPDATE items SET starting_bid = 75, desc_placeholder = 'A rich and dramatic floral portrait showcasing a purple flower in exquisite detail. The deep violet tones and velvet textures create a sophisticated, elegant, and timeless botanical statement.' WHERE creative_name = 'Violet Blossom';
UPDATE items SET starting_bid = 150, desc_placeholder = 'A unique, tall-format canvas featuring a flower in a kaleidoscope of rainbow hues. Captivating, radiant, and energetic, it brings a cheerful burst of color to any narrow wall space.' WHERE creative_name = 'Chromatic Flora';
